### PR TITLE
A big code reformat

### PR DESCRIPTION
**Pull request by xliucs**
Mainly on datalaoder and post-processing/metric.

### CODE REVIEW

**Review by girishvn — COMMENTED** [review]
@xliucs can you check that these are changes that have been made to main->head.
These changes seem to be from an older version of main. 
I don't believe 'self.dataset_name' is an active member of of 'self' for the baseloader class and extended classes

**Comment by xliucs** [comment]
@girishvn This is based on latest HEAD. `self.dataset_name ` is the new change. It was called `self.name`, and I don't think that is a proper name.

**Review by girishvn — APPROVED** [review]
Changed approved by @girishvn

**Comment by girishvn** [comment]
@yahskapar please view as well

**Pull request merged**
