### PR TITLE
Median bounding box

### PR DESCRIPTION
**Pull request by yahskapar**
- Added median bounding box feature that can help filter out erroneous detections 
- Updated config files are doing a small bit of refactoring that further split up the preprocessing section

Note that usage of dynamic detection and the median bounding box don't always help depending on the data at hand, so by default they're not used in all current config files. For the coming UBFC-PHYS PR, they will be used by default since it does appear to help quite a bit given the different types of natural motion and certain problematic clothing in the data. In the future, we may want to explore an alternate, possibly more robust yet fast face detector.

===PRE-TRAINED UBFC TESTED ON PURE===

Before median box changes:

FFT MAE (FFT Label):3.694385593220339
FFT RMSE (FFT Label):13.848831292145585
FFT MAPE (FFT Label):3.3882176381266618
FFT Pearson (FFT Label):0.8176110623563922

After median box changes (dynamic det freq 30):

FFT MAE (FFT Label):3.8731461864406778
FFT RMSE (FFT Label):14.052953550902807
FFT MAPE (FFT Label):4.414435806320214
FFT Pearson (FFT Label):0.8083655742963689

After median box changes (dynamic det freq 1):

FFT MAE (FFT Label):4.379634533898305
FFT RMSE (FFT Label):16.14613338947354
FFT MAPE (FFT Label):4.811864210762061
FFT Pearson (FFT Label):0.7457942330301349

===PRE-TRAINED PURE TESTED ON UBFC===

Before median box changes:

FFT MAE (FFT Label):1.2974330357142858
FFT RMSE (FFT Label):2.8704957923240366
FFT MAPE (FFT Label):1.500155568072648
FFT Pearson (FFT Label):0.9890524988652464

After median box changes (dynamic det freq 30):

FFT MAE (FFT Label):1.171875
FFT RMSE (FFT Label):2.8832820284012
FFT MAPE (FFT Label):1.3370964050134853
FFT Pearson (FFT Label):0.9879544284391218

After median box changes (dynamic det freq 1):

FFT MAE (FFT Label):1.1300223214285714
FFT RMSE (FFT Label):2.657562700846129
FFT MAPE (FFT Label):1.2837053516224317
FFT Pearson (FFT Label):0.9896922270384425

===UNSUPERVISED POS on UBFC===

Before median box changes:

FFT MAE (FFT Label):3.9969308035714284
FFT RMSE (FFT Label):7.5831059532071405
FFT MAPE (FFT Label):3.8622851481891742
FFT Pearson  (FFT Label):0.9224921893686093

After median box changes (dynamic det freq 30):

FFT MAE (FFT Label):4.896763392857143
FFT RMSE (FFT Label):11.21907479559467
FFT MAPE (FFT Label):4.639023406438588
FFT Pearson  (FFT Label):0.8283364883283528

After median box changes (dynamic det freq 1):

FFT MAE (FFT Label):4.729352678571429
FFT RMSE (FFT Label):10.654014272964092
FFT MAPE (FFT Label):4.495808225629422
FFT Pearson  (FFT Label):0.8444135960561804

===TRAIN/VALID on UBFC, TEST ON PURE===

With median box changes (dynamic det freq 30):

FFT MAE (FFT Label):4.215770656779661
FFT RMSE (FFT Label):15.28018990499106
FFT MAPE (FFT Label):4.314802487406652
FFT Pearson (FFT Label):0.7729950051652774

### CODE REVIEW

**Comment by xliucs** [comment]
@yahskapar , Can you also help update the BP4D config files? That PR just got merged.

**Review by xliucs — CHANGES_REQUESTED** [review]
LGTM but see my comment.Please also update BP4D configs.

**Comment by yahskapar** [comment]
@xliucs Updated. I also fixed what looked like some minor mistakes in the B4PD config files (mainly due to the START and END float values, as well as one instance where the chunk length was 128 instead of 180).

**Comment by girishvn** [comment]
Went ahead and merged. Looks good to me, and fulfilled the requested changes to the BP4D config files.

**Pull request merged**
