### PR TITLE
code clean up: added comments, doc strings, and output spacing (for improved readability)

### PR DESCRIPTION
**Pull request by girishvn**
Tested preprocessing, train, validation, and test on PURE_PURE_UBFC_TSCAN

### CODE REVIEW

**Comment by girishvn** [comment]
@xliucs @yahskapar Please take a look. Thanks

**Review by xliucs — CHANGES_REQUESTED** [review]
Hi if you want to print a new line, you can use print("\n") I would suggest reading this https://www.freecodecamp.org/news/python-new-line-and-how-to-python-print-without-a-newline/

**Comment by xliucs** [comment]
Try to combine your print statements.

**Comment by girishvn** [comment]
commit changes. Combined print statements where possible

**Review by yahskapar — APPROVED** [review]
LGTM after some of the print statements were combined. I'm assuming since exemple.png was removed with this PR, the temp folder should be removed as well? It's not clear to me from the PR itself if that has already been done along with exemple.png being removed. Approving anyhow since that is a straightforward removal to update the PR with if needed.

**Review by xliucs — APPROVED** [review]

**Pull request merged**
