### PR TITLE
changing wording from normalized to diffnormalized

### PR DESCRIPTION
**Pull request by girishvn**
Changed occurrences of `Normalized` to `DiffNormalized`

Tested full pipeline w/ PURE_PURE_UBFC_TSCAN.yaml w/ preprocessing, training, and testing.
Results below: 

FFT MAE (FFT Label):1.2346540178571428
FFT RMSE (FFT Label):2.9557296788139373
FFT MAPE (FFT Label):1.4422882653073863
FFT Pearson (FFT Label):0.9886615545146553

### CODE REVIEW

**Comment by girishvn** [comment]
@xliucs @yahskapar

**Review by xliucs — COMMENTED** [review]
It looks good to me @girishvn. Can you make sure to run a training and an inference config file to ensure the pipeline is working? Thanks.

**Comment by xliucs** [comment]
Sorry, I just saw your results. Can you run an inference config? Also can you please update the pre-trained model filenames? There are two physnet_normalized.

**Comment by xliucs** [comment]
Otherwise, LGTM.

**Comment by girishvn** [comment]
Renamed requested model files, and ran with infer_configs/PURE_PURE_UBFC_TSCAN_BASIC.yaml w/ results as follows (same as expected):

FFT MAE (FFT Label):1.2346540178571428
FFT RMSE (FFT Label):2.9557296788139373
FFT MAPE (FFT Label):1.4422882653073863
FFT Pearson (FFT Label):0.9886615545146553

**Review by xliucs — APPROVED** [review]

**Pull request merged**
